### PR TITLE
Use Java-level double type results

### PR DESCRIPTION
**Pull request by xiaoye-2018**
Why do we need to call JS to convert the result here? Wouldn't it be better to just keep the double semantics at the Java level?

### CODE REVIEW

**Comment by caoccao** [comment]
E.g.

```
> 1.01.toString()
'1.01'
> 1e21.toString()
'1e+21'
> 1000.1.toString()
'1000.1'
> 1.23e20
123000000000000000000
> 1.23e21
1.23e+21
> 1.23e-21.toString()
'1.23e-21'
```

**Comment by xiaoye-2018** [comment]
I want to keep it directly so that it can be used in the Java layer. Because the Double in the Java layer will also be like this, I am not sure what it will affect
image

**Comment by caoccao** [comment]
Please use `getValue().toString()` instead.

**Comment by xiaoye-2018** [comment]
ok

**Pull request closed without merging**
