### PR TITLE
Infra/redesign docker build

### PR DESCRIPTION
**Pull request by amithgeorge**
Original PR discussion - https://github.com/caoccao/Javet/pull/197
Original Issue - https://github.com/caoccao/Javet/issues/171

I accidentally closed the previous PR. I have incorporated the changes as suggested on the previous PR. Please have a look. 

- Successful execution of workflow for building the base image - https://github.com/amithgeorge/Javet/actions/runs/3428737410

- Successful execution of workflow for building the image with grade deps - https://github.com/amithgeorge/Javet/actions/runs/3428737387

- Successful execution of workflow for building the artifact - https://github.com/amithgeorge/Javet/actions/runs/3428737407

Things that need to be updated

- [x] Docker Hub user name
- [x] Docker Hub repo name
- [ ] Instructions for which all variables need to be updated in the various build files

-----

In the repository, create three Repository level Action Secrets 
- `DOCKERHUB_USERNAME` 
- `DOCKERHUB_ACCESS_TOKEN` : the [Personal Access Token](https://docs.docker.com/docker-hub/access-tokens/) for the above mentioned user
- `DOCKERHUB_REPO_JAVET`: the name of the docker hub repository to which the images should be pushed. Must be owned by the above mentioned user. 

-----

When we need to update the version of either V8 or Node.js, or update the Javet artifact version, then make changes to the following files 

.github/workflows/linux_build_node_v8_image.yml
  - env JAVET_V8_VERSION
  - env JAVET_NODE_VERSION

.github/workflows/linux_build_dev_image.yml
  - env JAVET_V8_NODE_IMAGE_TAG
  - env JAVET_VERSION

.github/workflows/linux_build_artifact.yml
  - env JAVET_GRADLE_IMAGE_TAG

docker/linux-x86_64/base-v8.Dockerfile
  - ARG JAVET_V8_VERSION
  - version in Usage comment

docker/linux-x86_64/base-node.Dockerfile
  - ARG JAVET_NODE_VERSION
  - version in Usage comment

docker/linux-x86_64/v8_node.Dockerfile
  - ARG JAVET_V8_VERSION
  - ARG JAVET_NODE_VERSION
  - version in Usage comment

docker/linux-x86_64/gradle.Dockerfile
  - ARG JAVET_V8_NODE_IMAGE_TAG
  - version in Usage comment

docker/linux-x86_64/artifact.Dockerfile
  - ARG JAVET_GRADLE_IMAGE_TAG
  - version in Usage comment

### CODE REVIEW

**Comment by caoccao** [comment]
I just checked it out. It looks good to me. Thank you very much!

- Could you list all the variables I need to set up here?
- After I set the variable up, please update the PR and let's test if it works.
- Final check and merge.

Sounds good? Please let me know if you have any questions.

**Comment by caoccao** [comment]
Thank you for the update.

- I added github environment `Docker Hub` with a secret `DOCKERHUB_ACCESS_TOKEN`.
- As we discussed, could you change the docker user name to an ENV as well?
- And how about the docker repo naming convention? Currently I'm using `sjtucaocao/javet` for the Linux images, and `sjtucaocao/javet-android` for the Android images. May I know your preference? Then, I'll create the repos or reuse the existing ones. Also, I wonder if the repo names could be ENVs as well.

**Comment by josh-hemphill** [comment]
Do either of you have the image sizes you could post?
I want to try and match up my multi-stage implementation with this, but I don't want to bother trying to do too much of it if it creates bigger images.
(For clarification, when I say Multi-Stage, I'm talking about the [newer feature of docker](https://docs.docker.com/build/building/multi-stage/) that lets you create named layers and build chains that fork all inside a single file, though it also lets you specify other files as part of your context so you can create an image from any stage if you want, but otherwise it all only exists in the layer cache.)

**Comment by caoccao** [comment]
> Do either of you have the image sizes you could post? I want to try and match up my multi-stage implementation with this, but I don't want to bother trying to do too much of it if it creates bigger images. (For clarification, when I say Multi-Stage, I'm talking about the [newer feature of docker](https://docs.docker.com/build/building/multi-stage/) that lets you create named layers and build chains that fork all inside a single file, though it also lets you specify other files as part of your context so you can create an image from any stage if you want, but otherwise it all only exists in the layer cache.)

I think @amithgeorge did so in `docker/linux-x86_64/v8_node.Dockerfile`.

**Comment by amithgeorge** [comment]
@josh-hemphill All the images are present here - https://hub.docker.com/r/amithgeorge/javet-linux-dev/tags The following images are provided

```
base-jvm-latest - 550 MB
base-v8-10.7.193.16 (based off base-jvm-latest) - 2.82 GB
base-node-18.12.0 (based off base-jvm-latest) - 886 MB
v8-10.7.193.16_node-18.12.0 (based off base-v8-10.7.193.16 and base-node-18.12.0) - 2.87 GB
2.0.1 (based off v8-10.7.193.16_node-18.12.0) - 2.92 GB
```

I preferred separate images over a multi stage build, because I am making the assumption the intermediate images (v8, node) are useful in their own right, eg its possible to bump the version of one without bumping the version of the other, thus speeding my the creation of the final image.

**Comment by amithgeorge** [comment]
I have done the requested changes. 

One thing to note, the dockerfiles themselves still have hardcoded references to `sjtucaocao/javet`. I can replace this with build args later. I would prefer first confirming that the existing changes are working. And then in a separate PR or a new commit in the same PR, I can replace the hardcoded references. 

@caoccao are you able to manually execute trigger these workflows and test them? I will need some guidance on how workflows work in a cross repository PR. To simplify things, I could update the triggers such that the workflow runs on every push to this branch. What do you suggest?

**Pull request merged**
